/*
cilo for: nos permite iterar, cuando sabemos el tamaño, estructura de repeticion. 


*/

#include <iostream> 
using namespace std;



// int main(){

//     int num = 10;

//     for (int i = 1; i <= num; i++){
//         cout << "Hola mundo"<< endl;
//     }



//     return 0;
// }


int main(){
      int main(){
	
		double n1, porcentaje;

		cout << "Ingresa el monto: "; cin>>n1;

		porcentaje = n1 * 0.35;

		cout << "Tu parte a cobrar seria de: "<< porcentaje <<endl;

	return 0;
}



    return 0;
} 